const JWT_EXPIRY_DAYS = 7;

const BCRYPT_SALT_ROUNDS = 10;

const PAGINATION_DEFAULT_PAGE = 1;

const PAGINATION_DEFAULT_LIMIT = 20;

const PAGINATION_MAX_LIMIT = 100;

const RATE_LIMIT_GLOBAL_WINDOW_MS = 15 * 60 * 1000;

const RATE_LIMIT_GLOBAL_MAX = 100;

const RATE_LIMIT_LOGIN_WINDOW_MS = 15 * 60 * 1000;

const RATE_LIMIT_LOGIN_MAX = 10;

const RATE_LIMIT_ERROR_MESSAGE = 'Too many requests. Please try again later.';

const COOKIE_NAME = 'access_token';

const MILLISECONDS_PER_DAY = 24 * 60 * 60 * 1000;

const TREND_PERIOD_MONTHLY = 'monthly';

const TREND_PERIOD_WEEKLY = 'weekly';

const TREND_MONTHS_LOOKBACK = 6;

const TREND_WEEKS_LOOKBACK = 6;

const DASHBOARD_RECENT_ACTIVITY_LIMIT = 10;

const ISO_DATE_LENGTH = 10;

const USER_ROLES = Object.freeze({
  VIEWER: 'viewer',
  ANALYST: 'analyst',
  ADMIN: 'admin',
});

const USER_STATUSES = Object.freeze({
  ACTIVE: 'active',
  INACTIVE: 'inactive',
});

const RECORD_TYPES = Object.freeze({
  INCOME: 'income',
  EXPENSE: 'expense',
});

const SEED_DEMO_PLAINTEXT_PASSWORD = 'Password123!';

const SEED_FINANCIAL_RECORDS_COUNT = 30;

const HTTP_STATUS_CREATED = 201;

const HTTP_STATUS_CONFLICT = 409;

const HTTP_STATUS_TOO_MANY_REQUESTS = 429;

module.exports = {
  JWT_EXPIRY_DAYS,
  BCRYPT_SALT_ROUNDS,
  PAGINATION_DEFAULT_PAGE,
  PAGINATION_DEFAULT_LIMIT,
  PAGINATION_MAX_LIMIT,
  RATE_LIMIT_GLOBAL_WINDOW_MS,
  RATE_LIMIT_GLOBAL_MAX,
  RATE_LIMIT_LOGIN_WINDOW_MS,
  RATE_LIMIT_LOGIN_MAX,
  RATE_LIMIT_ERROR_MESSAGE,
  COOKIE_NAME,
  MILLISECONDS_PER_DAY,
  TREND_PERIOD_MONTHLY,
  TREND_PERIOD_WEEKLY,
  TREND_MONTHS_LOOKBACK,
  TREND_WEEKS_LOOKBACK,
  DASHBOARD_RECENT_ACTIVITY_LIMIT,
  ISO_DATE_LENGTH,
  USER_ROLES,
  USER_STATUSES,
  RECORD_TYPES,
  SEED_DEMO_PLAINTEXT_PASSWORD,
  SEED_FINANCIAL_RECORDS_COUNT,
  HTTP_STATUS_CREATED,
  HTTP_STATUS_CONFLICT,
  HTTP_STATUS_TOO_MANY_REQUESTS,
};
